/**
 * tif tiles are .tifs (shocking, I know)
 * Seams per tile are NOT corrected
 * Generated by external services such as a map server
 */
import * as GeoTiff from '../secondary/geotiff/geotiff'

export default function TifParser(
    tilePath: string,
    layerObj?: any,
    xyz?: any,
    tileResolution?: number,
    numberOfVertices?: number
): Promise<number[]> {
    return new Promise((resolve, reject) => {
        fetch(tilePath)
            .then((resp) => resp.arrayBuffer())
            .then((buffer) => {
                GeoTiff.fromArrayBuffer(buffer).then((tif) => {
                    tif.readRasters()
                        .then((rasters) => {
                            console.log(rasters)
                            console.log(rasters[0][0])
                            resolve(rasters[0])
                        })
                        .catch(() => {
                            reject()
                        })
                })
            })
            .catch(() => {
                reject()
            })
    })
}
